### ISSUE TITLE
YG_SurfaceDisturbance_July2022_BEACONS_EDIT.gpkg is corrupt

### ISSUE THREAD

**Issue by prvernier** [beaconsproject/dc-mapping#2]
The file "YG_SurfaceDisturbance_July2022_BEACONS_EDIT.gpkg" appears to be corrupt. There is a backup from the previous day. Check with Marc to see if there are any differences between the 2 versions. If they are the same, replace the corrupt version.

**Comment by edwardsmarc** [comment]
I'm able to open this file with no problem. At least the version on the shared Drive in the SPOT_2020_21/FDA_10ab folder.

Where are the files in this repo stored? Is it the Shared Drive or just a folder your copying files to on Dropbox?

**Comment by prvernier** [comment]
I still can't open this file - either the one on the shared Google drive or the one in the repository. And, I've tried with QGIS and R. When I use st_layers this is what I get:

> st_layers('YG_SurfaceDisturbance_July2022_BEACONS_EDIT.gpkg')
Cannot open data source G:\Shared drives\DC Mapping\digitizing\SPOT_2020_21\FDA_10ab\YG_SurfaceDisturbance_July2022_BEACONS_EDIT.gpkg
Error in CPL_get_layers(dsn, options, do_count) : Open failed.
In addition: Warning message:
In CPL_get_layers(dsn, options, do_count) :
  GDAL Error 1: database disk image is malformed

As for the repository files, I push and pull from a non-shared drive on my computer, as with other repositories. It means we currently have two sets of file, arranged somewhat differently, one on Google drive and the other in the repo. Not ideal - maybe we could eventually remove from Google drive the files/folders on Github. Or maybe you have other ideas?

**Comment by edwardsmarc** [comment]
Works for me with st_layers also. I tried closing my QGIS in case it was creating a lock. I also made a replicate using the sf package for you to test:

YG_SurfaceDisturbance_July2022_BEACONS_EDIT_TEST.gpkg

**Comment by prvernier** [comment]
That new one you created works for me. I still get the same error message for the other one.

**Comment by edwardsmarc** [comment]
Replaced with the new file and archived the corrupt one.
